# Generated by Django 3.2.18 on 2023-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sydnyofficial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
