# Generated by Django 3.2.18 on 2023-04-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sydnyofficial', '0003_audio_fanlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='fanlink',
            field=models.CharField(max_length=200),
        ),
    ]
